### ISSUE TITLE
An unhandled exception of type 'System.StackOverflowException' occurred in PowerCollections.dll

### ISSUE THREAD

**Issue by cmeans** [NetTopologySuite/PowerCollections#1]
Hi,

We're experiencing the subject exception during a call to STRtree<IGeometry>.Build().

We successfully inserted 654639 items (mostly LineString objects) into the tree.

The code ASP.NET v4.52 is running under IISExpress (64bit).
Using NetTopologySuite v1.14 installed via NuGet.

Any help/suggestions would be appreciated.

**Comment by DGuidi** [comment]
Do you have the stacktrace? Please copy Here. 

----- Messaggio originale -----
Da: "Chris Means" notifications@github.com
Inviato: ‎30/‎11/‎2015 21:34
A: "NetTopologySuite/PowerCollections" PowerCollections@noreply.github.com
Oggetto: [PowerCollections] An unhandled exception of type'System.StackOverflowException' occurred in PowerCollections.dll (#1)

Hi,
We're experiencing the subject exception during a call to STRtree.Build().
We successfully inserted 654639 items (mostly LineString objects) into the tree.
The code ASP.NET v4.52 is running under IISExpress (64bit).
Using NetTopologySuite v1.14 installed via NuGet.
Any help/suggestions would be appreciated.

**Comment by cmeans** [comment]
StackTrace doesn't appear to be possible from VS for the ASP.NET app.  I get the error:  "The maximum number of stack frames supported by Visual Studio has been exceeded."

Unfortunately, when I transferred the code to a 64bit Console app, the StackOverflowException was not thrown, and the STRtree.Build process appeared to complete without error.

Is there a VS setting you're aware of that I can use to get the info you need?

**Comment by DGuidi** [comment]
you can try using [elmah](https://code.google.com/p/elmah/)

**Comment by DGuidi** [comment]
please re-open when you have more info

**Comment by jaundice** [comment]
This may be related: http://blogs.msdn.com/b/clrcodegeneration/archive/2009/05/11/tail-call-improvements-in-net-framework-4.aspx Note that tail call optimization only applies to x64. There is no optimization for x86.
